image: alpine

before_script:
  - apk add curl --no-cache

Trigger godeps:
  script:
    - "curl -X POST -F token=76f0cdb3a851f0292dffc96d8e7003 -F ref=go-with-deps https://gitlab.com/api/v4/projects/5388949/trigger/pipeline"
