image: alpine

before_script:
  - apk add curl --no-cache

Trigger godeps:
  script:
    - "curl -X POST -F token=d1c6be120074b45bc379b1400872a9 -F ref=go-with-deps https://gitlab.com/api/v4/projects/5723176/trigger/pipeline